version: '3'

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: sprout/app:latest
    networks:
      - sprout
    volumes:
      - .:/var/www/html/public
    working_dir: /var/www/html/public
    ports:
      - "80:80"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    networks:
      - sprout
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  sprout:
    driver: bridge

volumes:
  dbdata:
    driver: local