#!/usr/bin/env bash

# Function that outputs Sprout is not running...
function sprout_is_not_running {
  echo -e "${WHITE}Sprout is not running.${NC}" >&2
  echo "" >&2
  echo -e "${WHITE}Sprout can be started using with:${NC} './vendor/bin/sprout up' or './vendor/bin/sprout up -d'" >&2
  exit 1
}

if [ $# -gt 0 ]; then

  # Bring Sprout up or down...
  if [ "$1" == "start" ] || [ "$1" == "up" ]; then
    docker-compose up -d
  elif [ "$1" == "stop" ] || [ "$1" == "down" ]; then
    docker-compose down

  # Run Composer commands
  elif [ "$1" == "composer" ]; then
    shift 1
    docker-compose exec \
      app \
      composer "$@"
  else
    # Default to passing commands to docker-compose...
    docker-compose "$@"
  fi

else
  docker-compose ps
fi
